apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm-app.fullname" . }}-app-ingress
  annotations:
      kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host:
    http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: {{ include "helm-app.fullname" . }}-app-service
            port:
              number: 5000
