apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-app.fullname" . }}-app-service
spec:
  type: {{ .Values.service.app.type }}
  selector:
    {{- include "helm-app.selectorLabels" . | nindent 4 }}
    app: app-wb
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000