apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-app.fullname" . }}-app-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
     {{- include "helm-app.selectorLabels" . | nindent 6 }}
      app: app-wb
  template:
    metadata:
      labels:
        {{- include "helm-app.selectorLabels" . | nindent 8 }}
        app: app-wb
    spec:
      {{- if .Values.Deployment.enabled }}
      {{- with .Values.Deployment.app_deploy }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: app-wb
        image: lonelyglare/creador-partidos-futbol:1.2
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: {{ .Values.Deployment.resources.limits.cpu }}
            memory: {{ .Values.Deployment.resources.limits.memory }}
          requests:
            cpu: {{ .Values.Deployment.resources.requests.cpu }}
            memory: {{ .Values.Deployment.resources.requests.memory }}
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "helm-app.fullname" . }}-user-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "helm-app.fullname" . }}-user-config
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ include "helm-app.fullname" . }}-db-config
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ include "helm-app.fullname" . }}-db-config
              key: MYSQL_HOST        
