apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-app.fullname" . }}-db-config
data:
  MYSQL_DATABASE: {{ .Values.Db.MYSQL_DATABASE }}
  MYSQL_HOST: {{ include "helm-app.fullname" . }}-{{ .Values.Db.MYSQL_HOST }}