apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: kp-practica
spec:
  type: LoadBalancer
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 6000