apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db-svc
  template:
    metadata:
      labels:
        app: db-svc
    spec:
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                    - app-wb
              topologyKey: "topology.kubernetes.io/hostname"
      containers:
      - name: db
        image: mysql:8.0
        envFrom:
        - configMapRef:
            name: db-config
        - secretRef:
            name: user-config
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: "2Gi"  # aumenta el límite de memoria a 2GB
            cpu: "1"       # aumenta la capacidad de procesamiento a 1 nucleo
          requests:
            memory: "1Gi"  # solicita al menos 1GB de memoria
            cpu: "0.5"
  volumeClaimTemplates:
  - metadata:
      name: db-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: db-svc
