
#ingressEnabled: true
### Ingress
ingressPort: 80

# Deployment
replicas: 1
resources:
  requests:
    memory: 1G
    cpu: 0.5M
  limits:
    memory: 2G
    cpu: 1M

#Database
Db:
  MYSQL_PASSWORD: dXNlcjEyMw== 
  MYSQL_ROOT_PASSWORD: cm9vdA== 
  MYSQL_USER: dXNlcg== 
  MYSQL_HOST: db 
  MYSQL_ROOT_PASSWORD: root


# HPA
HPA:
  enabled: true
  maxReplicas: 8
  minReplicas: 1
  targetCPUUtilizationPercentage: 70


