
#ingressEnabled: true
### Ingress
ingressPort: 80

# Deployment
Deployment:
  replicas: 1
  resources:
    requests:
      memory: 100M
      cpu: 10m
    limits:
      memory: 2G
      cpu: 2
  #Affinity    
  enabled: true
  app_deploy:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values: 
              - db
          topologyKey: "failure-domain.beta.kubernetes.io/zone"
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values: 
              - app-wb
          topologyKey: "failure-domain.beta.kubernetes.io/zone"


#Database
Db:
  MYSQL_PASSWORD: user123
  MYSQL_USER: user 
  MYSQL_HOST: db 
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: db-partidos

#Volumes
volumeMount: 
  name: db-storage
  size: 5Gi
  storageClass: standard

# HPA
HPA:
  enabled: true
  maxReplicas: 8
  minReplicas: 1
  targetCPUUtilizationPercentage: 70

#Service
service:
  app:
    type: LoadBalancer
  db:
    type: ClusterIP
