apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: kp-practica
spec:
  type: LoadBalancer
  selector:
    app: app-wb
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000