apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ## Al no especificar pasa a ser un cluster ip
  selector:
    app: pod-db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306