version: '3'

services:
  # 
  app:
    build: .
    image: amc/flask-1.0
    ports:
      - "5000:5000"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
    networks:
      - net
    depends_on:
      - db

  # 
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    networks:
      - net

networks:
  net:

volumes: 
  db_data: